import jsPDF from 'jspdf';
import { Tender } from '@/hooks/useTenders';

export const generateTenderPDF = (tender: Tender) => {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('TENDER PACKAGE', 105, 20, { align: 'center' });
  
  // Tender Title
  doc.setFontSize(16);
  doc.text(tender.title, 20, 35);
  
  // Status Badge
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Status: ${tender.status.toUpperCase()}`, 20, 45);
  
  // Section: Basic Information
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Basic Information', 20, 60);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  let yPos = 70;
  
  doc.text(`Issued by: ${tender.issued_by_profile?.name || 'Unknown'}`, 20, yPos);
  yPos += 7;
  
  doc.text(`Created: ${new Date(tender.created_at).toLocaleDateString()}`, 20, yPos);
  yPos += 7;
  
  doc.text(`Deadline: ${new Date(tender.deadline).toLocaleDateString()}`, 20, yPos);
  yPos += 7;
  
  if (tender.budget) {
    doc.text(`Budget: $${tender.budget.toLocaleString()}`, 20, yPos);
    yPos += 7;
  }
  
  if (tender.estimated_start_date) {
    doc.text(`Estimated Start: ${new Date(tender.estimated_start_date).toLocaleDateString()}`, 20, yPos);
    yPos += 7;
  }
  
  doc.text(`Bids Received: ${tender.bid_count || 0}`, 20, yPos);
  yPos += 15;
  
  // Section: Description
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Description', 20, yPos);
  yPos += 10;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const descriptionLines = doc.splitTextToSize(tender.description || 'No description provided', 170);
  doc.text(descriptionLines, 20, yPos);
  yPos += (descriptionLines.length * 7) + 10;
  
  // Section: Requirements
  if (tender.requirements) {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Requirements', 20, yPos);
    yPos += 10;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    if (tender.requirements.description) {
      const reqLines = doc.splitTextToSize(tender.requirements.description, 170);
      doc.text(reqLines, 20, yPos);
      yPos += (reqLines.length * 7) + 10;
    }
  }
  
  // Section: Construction Items (if available)
  if (tender.construction_items && tender.construction_items.length > 0) {
    if (yPos > 220) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Construction Items', 20, yPos);
    yPos += 10;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    tender.construction_items.forEach((item: any, index: number) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.text(`${index + 1}. ${item.description || item.name || item.title || 'Item'}`, 25, yPos);
      yPos += 7;
      
      if (item.quantity) {
        doc.text(`   Quantity: ${item.quantity}`, 30, yPos);
        yPos += 6;
      }
      
      if (item.unit) {
        doc.text(`   Unit: ${item.unit}`, 30, yPos);
        yPos += 6;
      }
      
      yPos += 3;
    });
  }
  
  // Section: Builder Information (if available)
  if (tender.builder_company_name) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Builder Information', 20, yPos);
    yPos += 10;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    doc.text(`Company: ${tender.builder_company_name}`, 20, yPos);
    yPos += 7;
    
    if (tender.builder_contact_person) {
      doc.text(`Contact Person: ${tender.builder_contact_person}`, 20, yPos);
      yPos += 7;
    }
    
    if (tender.builder_email) {
      doc.text(`Email: ${tender.builder_email}`, 20, yPos);
      yPos += 7;
    }
    
    if (tender.builder_phone) {
      doc.text(`Phone: ${tender.builder_phone}`, 20, yPos);
      yPos += 7;
    }
    
    if (tender.builder_address) {
      const addressLines = doc.splitTextToSize(`Address: ${tender.builder_address}`, 170);
      doc.text(addressLines, 20, yPos);
      yPos += (addressLines.length * 7);
    }
  }
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
    doc.text('Generated by STOREALite', 105, 290, { align: 'center' });
  }
  
  // Save the PDF
  doc.save(`Tender_${tender.title.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.pdf`);
};
