// This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';
import { mockSupabase } from './mockClient';

const SUPABASE_URL = "https://inibugusrzfihldvegrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluaWJ1Z3VzcnpmaWhsZHZlZ3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTg1ODUsImV4cCI6MjA3MjQzNDU4NX0.-EUl9WpiCqV1FjTzVTYLpGZVttcrbbfG6LS8AeRHpdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// MOCK CLIENT FOR DEBUGGING
export const supabase = mockSupabase;

/*
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
*/